const AUTH_REQUEST = "AUTH_REQUEST"
const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
const EMPLOYEE_REQUEST = "EMPLOYEE_REQUEST"
const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
const TIME_TRACKER_REQUEST = "TIME_TRACKER_REQUEST"
const EMPLOYEE_TASK_HISTORY_REQUEST = "EMPLOYEE_TASK_HISTORY_REQUEST"
const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST"
const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST"
const APPROVED_TASK_REQUEST = "APPROVED_TASK_REQUEST"
const TASK_APPROVE_REJECT_REQUEST = "TASK_APPROVE_REJECT_REQUEST"
const APPROVE_REJECT_ALL_TASK_REQUEST = "APPROVE_REJECT_ALL_TASK_REQUEST"
const CALENDER_TASK_REQUEST = "CALENDER_TASK_REQUEST"

export {
  AUTH_REQUEST,
  FORGOT_PASSWORD_REQUEST,
  RESET_PASSWORD_REQUEST,
  EMPLOYEE_REQUEST,
  ADD_TASK_REQUEST,
  TIME_TRACKER_REQUEST,
  DELETE_TASK_REQUEST,
  UPDATE_TASK_REQUEST,
  EMPLOYEE_TASK_HISTORY_REQUEST,
  TASK_APPROVE_REJECT_REQUEST,
  APPROVE_REJECT_ALL_TASK_REQUEST,
  CALENDER_TASK_REQUEST,
  APPROVED_TASK_REQUEST,
}
